// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNulm2GSgPPNHS9uvbde71JARMrowLu7U',
    appId: '1:973280273499:web:fbbddcf4da9344ba7b4b7e',
    messagingSenderId: '973280273499',
    projectId: 'black-monitor-451210-i1',
    authDomain: 'black-monitor-451210-i1.firebaseapp.com',
    storageBucket: 'black-monitor-451210-i1.firebasestorage.app',
    measurementId: 'G-XPNM3QN823',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7usCVpBoheUQufgSpZ2WVWko7gCH7t0w',
    appId: '1:973280273499:android:131529fab802dfc17b4b7e',
    messagingSenderId: '973280273499',
    projectId: 'black-monitor-451210-i1',
    storageBucket: 'black-monitor-451210-i1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGE7Nlyy51j-omAmawaUNDFslexopQnog',
    appId: '1:973280273499:ios:a5efd9851908d5377b4b7e',
    messagingSenderId: '973280273499',
    projectId: 'black-monitor-451210-i1',
    storageBucket: 'black-monitor-451210-i1.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGE7Nlyy51j-omAmawaUNDFslexopQnog',
    appId: '1:973280273499:ios:a5efd9851908d5377b4b7e',
    messagingSenderId: '973280273499',
    projectId: 'black-monitor-451210-i1',
    storageBucket: 'black-monitor-451210-i1.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNulm2GSgPPNHS9uvbde71JARMrowLu7U',
    appId: '1:973280273499:web:7ed4c8c70b8085c97b4b7e',
    messagingSenderId: '973280273499',
    projectId: 'black-monitor-451210-i1',
    authDomain: 'black-monitor-451210-i1.firebaseapp.com',
    storageBucket: 'black-monitor-451210-i1.firebasestorage.app',
    measurementId: 'G-4KSL3Z062H',
  );
}
